version: '3'
services:
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    ports:
      - 3000:3000
    restart: always
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    expose:
      - 9090
    restart: always
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    expose:
      - 9100
    restart: always

volumes:
  grafana_data:
  grafana_logs:
  prometheus_data:
